create table if not exists public.bgm_tracks (
  id bigint generated by default as identity primary key,
  storage_path text not null unique,
  title text not null,
  artist text not null default 'GLIM',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint bgm_tracks_storage_path_check check (
    storage_path = btrim(storage_path)
    and storage_path <> ''
    and storage_path !~ '(^|/)\.\.(/|$)'
  ),
  constraint bgm_tracks_title_check check (
    title = btrim(title) and char_length(title) between 1 and 120
  ),
  constraint bgm_tracks_artist_check check (
    artist = btrim(artist) and char_length(artist) between 1 and 120
  )
);

alter table public.bgm_tracks enable row level security;

revoke all privileges on table public.bgm_tracks from public, anon, authenticated;
grant select on table public.bgm_tracks to anon, authenticated;
grant insert, update, delete on table public.bgm_tracks to authenticated;

drop policy if exists "Active BGM tracks are publicly readable"
  on public.bgm_tracks;
create policy "Active BGM tracks are publicly readable"
  on public.bgm_tracks
  for select
  to anon, authenticated
  using (is_active or (select public.is_moderator()));

drop policy if exists "Moderators can insert BGM tracks"
  on public.bgm_tracks;
create policy "Moderators can insert BGM tracks"
  on public.bgm_tracks
  for insert
  to authenticated
  with check ((select public.is_moderator()));

drop policy if exists "Moderators can update BGM tracks"
  on public.bgm_tracks;
create policy "Moderators can update BGM tracks"
  on public.bgm_tracks
  for update
  to authenticated
  using ((select public.is_moderator()))
  with check ((select public.is_moderator()));

drop policy if exists "Moderators can delete BGM tracks"
  on public.bgm_tracks;
create policy "Moderators can delete BGM tracks"
  on public.bgm_tracks
  for delete
  to authenticated
  using ((select public.is_moderator()));

drop policy if exists "Moderators can upload bgm"
  on storage.objects;
create policy "Moderators can upload bgm"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'bgm'
    and (select public.is_moderator())
  );

drop policy if exists "Moderators can update bgm"
  on storage.objects;
create policy "Moderators can update bgm"
  on storage.objects
  for update
  to authenticated
  using (
    bucket_id = 'bgm'
    and (select public.is_moderator())
  )
  with check (
    bucket_id = 'bgm'
    and (select public.is_moderator())
  );

drop policy if exists "Moderators can delete bgm"
  on storage.objects;
create policy "Moderators can delete bgm"
  on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'bgm'
    and (select public.is_moderator())
  );

insert into public.bgm_tracks (storage_path, title, artist, sort_order)
values
  ('Paper Cup Piano.mp3', 'Paper Cup Piano', 'GLIM', 10),
  ('Paper Boat After Rain.mp3', 'Paper boat After Rain', 'GLIM', 20)
on conflict (storage_path) do update
set
  title = excluded.title,
  artist = excluded.artist,
  sort_order = excluded.sort_order;
